# Generated by ChatGPT, and modified.
from pygltflib import GLTF2
import os

exclude_for_collision_addition_paths = []

def glb_to_gltf(glb_path, output_path, only_rename: bool):
    # Load .glb file
    gltf = GLTF2().load(glb_path)
    if gltf == None:
        print("Empty GLTF.")
        return

    # Modify node names
    if gltf.nodes:
        for node in gltf.nodes:
            if node.name:
                node.name = node.name.replace("-", "_") + ("" if only_rename else "$col")

    if gltf.animations:
        for anime in gltf.animations:
            if anime.name:
                anime.name = anime.name.replace("-", "_")

    # Save as .gltf (JSON text)
    gltf.save_binary(output_path)
    print(f"[done] Saved modified glb to: {output_path.split("music_box_serene_garden/")[-1]}")


def scan_and_convert(root_dir):
    for dirpath, dirnames, filenames in os.walk(root_dir):
        for filename in filenames:
            if filename.lower().endswith(".glb") and not filename.lower().endswith("$col.glb"):
                glb_path = os.path.join(dirpath, filename)
                glb_path_in_project = glb_path.split("music_box_serene_garden/")[-1]
                only_rename = glb_path_in_project in exclude_for_collision_addition_paths 
                output_path = os.path.splitext(glb_path)[0] + (".glb" if only_rename else "$col.glb")
                glb_to_gltf(
                    glb_path, output_path.replace("-", "_"),
                    only_rename
                )
                if not only_rename:
                    os.remove(glb_path)


if __name__ == "__main__":
    current_dir = os.path.dirname(os.path.abspath(__file__))
    print(f"Scanning directory: {current_dir}")
    scan_and_convert(current_dir)
